CREATE DATABASE IF NOT EXISTS hospital
  CHARACTER SET utf8
  COLLATE utf8_general_ci;
USE hospital;

CREATE TABLE IF NOT EXISTS district (
  ID   INT          NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(150) NOT NULL,
  UNIQUE (NAME),
  PRIMARY KEY (id)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS hospital (
  ID          INT          NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(150) NOT NULL,
  ADDRESS     VARCHAR(150) NOT NULL,
  DISTRICT_ID INT          NOT NULL,
  CONSTRAINT FK_DISTRICT_1 FOREIGN KEY (DISTRICT_ID)
  REFERENCES district (id),
  UNIQUE (NAME),
  PRIMARY KEY (id)
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS users (
  ID       INT         NOT NULL AUTO_INCREMENT,
  USERNAME    VARCHAR(255) NOT NULL,
  EMAIL    VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  STATUS   TINYINT(1)  NOT NULL DEFAULT 0,
  UNIQUE (LOGIN),
  UNIQUE (EMAIL),
  PRIMARY KEY (ID)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS role (
  ROLE VARCHAR(100) NOT NULL,
  PRIMARY KEY (ROLE)
)
  ENGINE = InnoDB
  CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS user_roles (
  USER_ID INT         NOT NULL,
  ROLE VARCHAR(100) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE),
  CONSTRAINT FK_USER_ROLE_DETAIL_1 FOREIGN KEY (USER_ID)
  REFERENCES users (ID),
  CONSTRAINT FK_USER_ROLE_DETAIL_2 FOREIGN KEY (ROLE)
  REFERENCES role (ROLE)
)
  ENGINE = InnoDB
  CHARACTER SET = UTF8;